var bbox="";function getTongdunFingerPrint(){!(function(){_fmOpt={partner:'pagsmile',appName:'pagsmile_web',token:'pagsmile'+"-"+new Date().getTime()+"-"+Math.random().toString(16).substr(2),fpHost:'https://usfp.tongdun.net',fmb:true,success:function(data){bbox=data;},};var fm=document.createElement('script');fm.type='text/javascript';fm.async=true;fm.src='https://static.tongdun.net/us/fm.js?ver=0.1&t='+(new Date().getTime()/3600000).toFixed(0);var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(fm,s);String.prototype.trim||!function(){var e=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;String.prototype.trim=function(){return this.replace(e,"")}}();var JSON=JSON||{};JSON.parse||!function(){JSON.parse=function(obj){"use strict";return eval("("+obj+")")}}(),JSON.stringify||!function(){JSON.stringify=function(e){var t=typeof e;if("object"!=t||null===e)return "string"==t&&(e='"'+e+'"'),String(e);var n,r,o=[],i=e&&e.constructor==Array;for(n in e)r=e[n],t=typeof r,"string"==t?r='"'+r+'"':"object"==t&&null!==r&&(r=JSON.stringify(r)),"function"!==t&&o.push((i?"":'"'+n+'":')+String(r));return(i?"[":"{")+String(o)+(i?"]":"}")}}(),Array.prototype.filter||!function(){Array.prototype.filter=function(e){"use strict";if(void 0===this||null===this)throw new TypeError;var t=Object(this),n=t.length>>>0;if("function"!=typeof e)throw new TypeError;for(var r=[],o=arguments.length>=2?arguments[1]:void 0,i=0;n>i;i++)
if(i in t){var a=t[i];e.call(o,a,i,t)&&r.push(a)}return r}}(),Array.prototype.forEach||(Array.prototype.forEach=function(e,t){"use strict";var n,r;if(null==this)throw new TypeError("this is null or not defined");var o,i=Object(this),a=i.length>>>0;if("[object Function]"!=={}.toString.call(e))throw new TypeError(e+" is not a function");for(arguments.length>=2&&(n=t),r=0;a>r;)r in i&&(o=i[r],e.call(n,o,r,i)),r++}),document.querySelectorAll||!function(){document.querySelectorAll=function(e){var t,n=document.createElement("style"),r=[];for(document.documentElement.firstChild.appendChild(n),document._qsa=[],n.styleSheet.cssText=e+"{x-qsa:expression(document._qsa && document._qsa.push(this))}",window.scrollBy(0,0),n.parentNode.removeChild(n);document._qsa.length;)t=document._qsa.shift(),t.style.removeAttribute("x-qsa"),r.push(t);return document._qsa=null,r}}(),document.querySelector||!function(){document.querySelector=function(e){var t=document.querySelectorAll(e);return t.length?t[0]:null}}()})()}
function getForterFingerPrint(siteID){try{document.addEventListener("ftr:tokenReady",function(evt){bbox=evt.detail;});(function(){var eu="22g4zl{5jf5fjtlv1forxgiurqw1qhw2vwdwxv";var siteId=siteID;function t(t,e){for(var n=t.split(""),r=0;r<n.length;++r)n[r]=String.fromCharCode(n[r].charCodeAt(0)+e);return n.join("");}
function e(e){return t(e,-_).replace(/%SN%/g,siteId);}
function n(){var t="no"+"op"+"fn",e="g"+"a",n="n"+"ame";return window[e]&&window[e][n]===t;}
function r(){return!(!navigator.brave||"function"!=typeof navigator.brave.isBrave);}
function o(){return document.currentScript&&document.currentScript.src;}
function i(t){try{(F.ex=t),n()&&-1===F.ex.indexOf(E.uB)&&(F.ex+=E.uB),r()&&-1===F.ex.indexOf(E.uBr)&&(F.ex+=E.uBr),o()&&-1===F.ex.indexOf(E.nIL)&&(F.ex+=E.nIL),window.ftr__snp_cwc||(F.ex+=E.s),q(F);}catch(t){}}
function a(t,e){function n(o){try{o.blockedURI===t&&(e(),document.removeEventListener(r,n));}catch(t){document.removeEventListener(r,n);}}
var r="securitypolicyviolation";document.addEventListener(r,n),setTimeout(function(){document.removeEventListener(r,n);},2*60*1e3);}
function c(t,e,n,r){var o=!1;(t="https://"+t),a(t,function(){r(!0),(o=!0);});var i=document.createElement("script");(i.onerror=function(){if(!o)
try{r(!1),(o=!0);}catch(t){}}),(i.onload=n),(i.type="text/javascript"),(i.id="ftr__script"),(i.async=!0),(i.src=t);var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(i,c);}
function u(t,e,n){var r=!1,o=new XMLHttpRequest();if((a(t,function(){n(new Error("CSP Violation"),!0),(r=!0);}),"withCredentials"in o))
o.open("GET",t,!0);else{if("undefined"==typeof XDomainRequest)return;(o=new XDomainRequest()),o.open("GET",t);}
(o.onload=function(){"function"==typeof e&&e(o);}),(o.onerror=function(t){if("function"==typeof n&&!r)
try{n(t,!1),(r=!0);}catch(t){}}),(o.onprogress=function(){}),(o.ontimeout=function(){"function"==typeof n&&n("tim"+"eo"+"ut",!1);}),setTimeout(function(){o.send();},0);}
function d(){u(y,function(n){try{var r=n.getAllResponseHeaders().toLowerCase();if(r.indexOf(x.toLowerCase())<0)return;var o=n.getResponseHeader(x),i=t(o,-_-1);if(i){var a=i.split(":");if(a&&3===a.length){var c=a[0],u=a[1],d=a[2];switch(u){case "none":A=c+T;break;case "res":A=c+T+d;break;case "enc":A=c+e("1forxgiurqw1qhw2vq2(VQ(2vfulsw1mv");break;case "enc-res":for(var s="",v=0,l=0;v<20;++v)
s+=v%3>0&&l<12?siteId.charAt(l++):F.id.charAt(v);var m=d.split(".");if(m.length>1){var h=m[0],w=m[1];A=c+T+h+"."+s+"."+w;break;}
if(r.indexOf(S.toLowerCase())>=0){var p=n.getResponseHeader(S),g=t(p,-_-1);window.ftr__altd=g;}
j(E.dUAL),setTimeout(f,U,E.dUAL);}}}}catch(t){}},function(t,e){i(e?E.uAS+E.cP:E.uAS);});}
function f(t){try{var e=t===E.uDF?L:A;if(!e)return;c(e,void 0,function(){try{Q(),i(t+E.uS);}catch(t){}},function(e){try{Q(),(F.td=1*new Date()-F.ts),i(e?t+E.uF+E.cP:t+E.uF),t===E.uDF&&d();}catch(t){i(E.eUoe);}});}catch(e){i(t+E.eTlu);}}
var s="fort",v="erTo",l="ken",m=s+v+l,h=10,w={write:function(t,e,n,r){void 0===r&&(r=!0);var o,i;if((n?((o=new Date()),o.setTime(o.getTime()+24*n*60*60*1e3),(i="; expires="+o.toGMTString())):(i=""),!r))
return void(document.cookie=escape(t)+"="+escape(e)+i+"; path=/");for(var a=1,c=document.domain.split("."),u=h,d=!0;d&&c.length>=a&&u>0;){var f=c.slice(-a).join(".");document.cookie=escape(t)+"="+escape(e)+i+"; path=/; domain="+f;var s=w.read(t);(null!=s&&s==e)||((f="."+f),(document.cookie=escape(t)+"="+escape(e)+i+"; path=/; domain="+f)),(d=-1===document.cookie.indexOf(t+"="+e)),a++,u--;}},read:function(t){var e=null;try{for(var n=escape(t)+"=",r=document.cookie.split(";"),o=32,i=0;i<r.length;i++){for(var a=r[i];a.charCodeAt(0)===o;)a=a.substring(1,a.length);0===a.indexOf(n)&&(e=unescape(a.substring(n.length,a.length)));}}finally{return e;}},},p="14";p+="ck";var g=function(t){if(document.head){var e=(function(){var e=document.createElement("link");return(e.setAttribute("rel","pre"+"con"+"nect"),e.setAttribute("cros"+"sori"+"gin","anonymous"),(e.onload=function(){document.head.removeChild(e);}),(e.onerror=function(t){document.head.removeChild(e);}),e.setAttribute("href",t),document.head.appendChild(e),e);})();setTimeout(function(){document.head.removeChild(e);},3e3);}},_=3,y=e(eu||"22g4zl{5jf5fjtlv1forxgiurqw1qhw2vwdwxv"),T=t("1forxgiurqw1qhw2",-_),x=t("[0Uhtxhvw0LG",-_),S=t("[0Fruuhodwlrq0LG",-_),A,L=e("(VQ(1fgq71iruwhu1frp2vq2(VQ(2vfulsw1mv"),k=e("(VQ(1fgq71iruwhu1frp2vqV2(VQ(2vfulsw1mv"),U=10;window.ftr__startScriptLoad=1*new Date();var D=function(t){var e="ft"+"r:tok"+"enR"+"eady";window.ftr__tt&&clearTimeout(window.ftr__tt),(window.ftr__tt=setTimeout(function(){try{delete window.ftr__tt,(t+="_tt");var n=document.createEvent("Event");n.initEvent(e,!1,!1),(n.detail=t),document.dispatchEvent(n);}catch(t){}},1e3));},q=function(t){var e=function(t){return t||"";},n=e(t.id)+"_"+e(t.ts)+"_"+e(t.td)+"_"+e(t.ex)+"_"+e(p);w.write(m,n,1825,!0),D(n),(window.ftr__gt=n);},V=function(){var t=w.read(m)||"",e=t.split("_"),n=function(t){return e[t]||void 0;};return{id:n(0),ts:n(1),td:n(2),ex:n(3),vr:n(4),};},b=(function(){for(var t={},e="fgu",n=[],r=0;r<256;r++)n[r]=(r<16?"0":"")+r.toString(16);var o=function(t,e,r,o,i){var a=i?"-":"";return(n[255&t]+
n[(t>>8)&255]+
n[(t>>16)&255]+
n[(t>>24)&255]+
a+
n[255&e]+
n[(e>>8)&255]+
a+
n[((e>>16)&15)|64]+
n[(e>>24)&255]+
a+
n[(63&r)|128]+
n[(r>>8)&255]+
a+
n[(r>>16)&255]+
n[(r>>24)&255]+
n[255&o]+
n[(o>>8)&255]+
n[(o>>16)&255]+
n[(o>>24)&255]);},i=function(){if(window.Uint32Array&&window.crypto&&window.crypto.getRandomValues){var t=new window.Uint32Array(4);return(window.crypto.getRandomValues(t),{d0:t[0],d1:t[1],d2:t[2],d3:t[3],});}
return{d0:(4294967296*Math.random())>>>0,d1:(4294967296*Math.random())>>>0,d2:(4294967296*Math.random())>>>0,d3:(4294967296*Math.random())>>>0,};},a=function(){var t="",e=function(t,e){for(var n="",r=t;r>0;--r)n+=e.charAt((1e3*Math.random())%e.length);return n;};return(t+=e(2,"0123456789")),(t+=e(1,"123456789")),(t+=e(8,"0123456789"));};return((t.safeGenerateNoDash=function(){try{var t=i();return o(t.d0,t.d1,t.d2,t.d3,!1);}catch(t){try{return e+a();}catch(t){}}}),(t.isValidNumericalToken=function(t){return(t&&t.toString().length<=11&&t.length>=9&&parseInt(t,10).toString().length<=11&&parseInt(t,10).toString().length>=9);}),(t.isValidUUIDToken=function(t){return t&&32===t.toString().length&&/^[a-z0-9]+$/.test(t);}),(t.isValidFGUToken=function(t){return 0==t.indexOf(e)&&t.length>=12;}),t);})(),E={uDF:"UDF",dUAL:"dUAL",uAS:"UAS",mLd:"1",eTlu:"2",eUoe:"3",uS:"4",uF:"9",tmos:["T5","T10","T15","T30","T60"],tmosSecs:[5,10,15,30,60],bIR:"43",uB:"u",uBr:"b",cP:"c",nIL:"i",s:"s",},C=function(t,e){for(var n=E.tmos,r=0;r<n.length;r++)if(t+n[r]===e)return!0;return!1;};try{var F=V();try{F.id&&(b.isValidNumericalToken(F.id)||b.isValidUUIDToken(F.id)||b.isValidFGUToken(F.id))?(window.ftr__ncd=!1):((F.id=b.safeGenerateNoDash()),(window.ftr__ncd=!0)),(F.ts=window.ftr__startScriptLoad),q(F),(window.ftr__snp_cwc=!!w.read(m)),window.ftr__snp_cwc||(L=k);for(var I="for"+"ter"+".co"+"m",R="ht"+"tps://c"+"dn9."+I,B="ht"+"tps://"+F.id+"-"+siteId+".cd"+"n."+I,G="http"+"s://cd"+"n3."+I,O=[R,B,G],M=0;M<O.length;M++)
g(O[M]);var N=new Array(E.tmosSecs.length),j=function(t){for(var e=0;e<E.tmosSecs.length;e++)N[e]=setTimeout(i,1e3*E.tmosSecs[e],t+E.tmos[e]);},Q=function(){for(var t=0;t<E.tmosSecs.length;t++)clearTimeout(N[t]);};C(E.uDF,F.ex)?loadAlternate():(j(E.uDF),setTimeout(f,U,E.uDF));}catch(t){i(E.mLd);}}catch(t){}})();}catch(error){}}
function getFingerPrint(globalPagsmileEnv,globalPagsmileAppId,globalPagsmilePublicKey){var xhr=new XMLHttpRequest();var url="";if(globalPagsmileEnv=="prod"){url="https://gateway.pagsmile.com/trade/rmsp";}else{url="https://gateway-test.pagsmile.com/trade/rmsp";}
var data={"app_id":globalPagsmileAppId,"timestamp":new Date(+new Date()+8*3600*1000).toJSON().substr(0,19).replace("T"," ")}
xhr.open("POST",url,true);xhr.setRequestHeader("Content-type","application/json");xhr.setRequestHeader("Authorization","Basic "+window.btoa(globalPagsmileAppId+":"+globalPagsmilePublicKey));xhr.send(JSON.stringify(data));xhr.onreadystatechange=function(){if(xhr.readyState==4){if(xhr.status==200){var resData=JSON.parse(xhr.response)
var provider=resData?.rmsp?.provider;var siteId=resData?.rmsp?.site_id;if(provider=="Forter"){getForterFingerPrint(siteId);}else{getTongdunFingerPrint();}}else{getTongdunFingerPrint();}}}}
var Pagsmile={state:{auth:{},pagsmileFormSubmit:false},addEvent:function(el,eventName,handler){if(el.addEventListener){try{el.addEventListener(eventName,handler);}catch(e){console.log(e);}}else{el.attachEvent('on'+eventName,function(){handler.call(el);});}},createXhr:function(auth,data,pagsmile_env,xhrCb){let self=this;self.state.pagsmileFormSubmit=true;let url="";if(pagsmile_env=="prod"){url="https://security.pagsmile.com/card/token";}else{url="https://security-test.pagsmile.com/card/token";}
var xhr=new XMLHttpRequest();xhr.open("POST",url,true);xhr.setRequestHeader("Content-type","application/json");xhr.setRequestHeader("Authorization","Basic "+window.btoa(auth.pagsmile_app_id+":"+auth.pagsmile_public_key));xhr.send(JSON.stringify(data));xhr.onreadystatechange=function(){self.state.pagsmileFormSubmit=false;if(xhr.readyState==4){if(xhr.status==200){xhrCb(xhr.response);}}}},createXhrSync:function(auth,data,pagsmile_env,xhrCb,sync){let self=this;if(sync===undefined){sync=false;}
self.state.pagsmileFormSubmit=true;var url=""
if(pagsmile_env=="prod"){url="https://security.pagsmile.com/card/token";}else{url="https://security-test.pagsmile.com/card/token";}
var xhr=new XMLHttpRequest();xhr.open("POST",url,!sync)
xhr.setRequestHeader("Content-type","application/json");xhr.setRequestHeader("Authorization","Basic "+window.btoa(auth.pagsmile_app_id+":"+auth.pagsmile_public_key));xhr.send(JSON.stringify(data));if(sync==false){xhr.onreadystatechange=function(){self.state.pagsmileFormSubmit=false
if(xhr.readyState==4){if(xhr.status==200){return xhrCb(xhr.response);}}}}else{self.state.pagsmileFormSubmit=false;if(xhr.readyState==4&&xhr.status==200){return xhrCb(xhr.response);}}},setPublishableKey:function(pagsmile_app_id,pagsmile_public_key,pagsmile_env){if(!pagsmile_app_id){throw new Error("Parameter missing pagsmile_app_id");}
if(!pagsmile_public_key){throw new Error("Parameter missing pagsmile_public_key");}
if(!pagsmile_env){throw new Error("Parameter missing pagsmile_env");}
this.state.auth.pagsmile_app_id=pagsmile_app_id;this.state.auth.pagsmile_public_key=pagsmile_public_key;this.state.pagsmile_env=pagsmile_env;getFingerPrint(pagsmile_env,pagsmile_app_id,pagsmile_public_key)},verifyFormData:function(){var formError=[];var formData={};var _year=document.querySelector('input[data-checkout="pagsmileCardExpirationYear"]')?.value;var _yearBySct=document.querySelector('select[data-checkout="pagsmileCardExpirationYear"]');var _yearBySctIndex=_yearBySct?.selectedIndex;var _yearBySctValue=_yearBySct?.options[_yearBySctIndex]?_yearBySct?.options[_yearBySctIndex].value:"";var _month=document.querySelector('input[data-checkout="pagsmileCardExpirationMonth"]')?.value;var _monthBySct=document.querySelector('select[data-checkout="pagsmileCardExpirationMonth"]');var _monthBySctIndex=_monthBySct?.selectedIndex;var _monthBySctValue=_monthBySct?.options[_monthBySctIndex]?_monthBySct?.options[_monthBySctIndex].value:"";var _card_no=document.querySelector('input[data-checkout="pagsmileCardNumber"]').value;var _cvv=document.querySelector('input[data-checkout="pagsmileSecurityCode"]').value;var _name=document.querySelector('input[data-checkout="pagsmileCardholderName"]').value;var docTypeEle=document.querySelector('select[data-checkout="pagsmileDocType"]');var _doc_type_index=docTypeEle.selectedIndex;var _doc_type_value=docTypeEle.options[_doc_type_index]?docTypeEle.options[_doc_type_index].value:"";var _doc_number=document.querySelector('input[data-checkout="pagsmileDocNumber"]').value;var YEAR=_year||_yearBySctValue;var MONTH=_month||_monthBySctValue;if(!_card_no){formError.push("card number field is required");}else if(!/^[0-9 ]+$/.test(_card_no)){formError.push("card number field is invalid");}else{formData._card_no=_card_no.replace(/\s*/g,"");}
if(!_cvv){formError.push("security code field is required");}else if(!/^\d+$/.test(_cvv)){formError.push("security code field is invalid");}else{formData._cvv=_cvv;}
if(!YEAR){formError.push("card expiration year field is required");}else if(!/^\d+$/.test(YEAR)){formError.push("card expiration year field is invalid");}else{formData._year=YEAR;}
if(!MONTH){formError.push("card expiration month field is required");}else if(!/^\d+$/.test(MONTH)){formError.push("card expiration month field is invalid");}else{formData._month=MONTH;}
if(!_name){formError.push("card holder name field is required");}else{formData._name=_name;}
if(_doc_type_value){formData._doc_type=_doc_type_value;}
if(_doc_number){formData._doc_number=_doc_number;}
return{"formError":formError,"formData":formData}},createToken(formEle,cb){var formErrorRes=this.verifyFormData().formError;var formData=this.verifyFormData().formData;if(formErrorRes.length>0){cb({status:-1,message:formErrorRes.join("; ")})}else{var auth=this.state.auth;var pagsmile_env=this.state.pagsmile_env;var data={"app_id":auth.pagsmile_app_id,"version":"2.0","card":{"valid_thru_year":formData._year,"valid_thru_month":formData._month,"cvv":formData._cvv,"card_no":formData._card_no,"holder":{"name":formData._name,"identification":{"type":formData._doc_type,"number":formData._doc_number}}},"timestamp":new Date(+new Date()+8*3600*1000).toJSON().substr(0,19).replace("T"," ")}
if(this.state.pagsmileFormSubmit){return false;}
this.createXhr(auth,data,pagsmile_env,function(res){var res=JSON.parse(res);if(res.code==10000){document.querySelector("#pagsmileToken").setAttribute('value',res.token)
document.querySelector("#pagsmileFingerprint").setAttribute('value',bbox)
cb&&cb({status:200,message:"create token success"})}else{cb&&cb({status:res.code,message:res.msg})}})}},createTokenSync(formEle,sync,cb){var formErrorRes=this.verifyFormData().formError;var formData=this.verifyFormData().formData;if(formErrorRes.length>0){cb({status:-1,message:formErrorRes.join("; ")})}else{var auth=this.state.auth;var pagsmile_env=this.state.pagsmile_env;var data={"app_id":auth.pagsmile_app_id,"version":"2.0","card":{"valid_thru_year":formData._year,"valid_thru_month":formData._month,"cvv":formData._cvv,"card_no":formData._card_no,"holder":{"name":formData._name,"identification":{"type":formData._doc_type,"number":formData._doc_number}}},"timestamp":new Date(+new Date()+8*3600*1000).toJSON().substr(0,19).replace("T"," ")}
if(this.state.pagsmileFormSubmit){return false;}
return this.createXhrSync(auth,data,pagsmile_env,function(res){if(!bbox){return{status:500,message:"Initialization failed, please try again"}}
var res=JSON.parse(res);if(res.code==10000){document.querySelector("#pagsmileToken").setAttribute('value',res.token)
document.querySelector("#pagsmileFingerprint").setAttribute('value',bbox)
cb&&cb({status:200,message:"create token success"})
return{token:res.token,fingerprint:bbox}}else{cb&&cb({status:res.code,message:res.msg})
return{}}},sync)}},preRequisites:{loadScript:function(url,id){return new Promise((resolve,reject)=>{const existingScript=document.getElementById(id);if(!existingScript){const script=document.createElement("script");script.src=url;script.id=id;document.body.appendChild(script);script.onload=()=>{resolve();};script.onerror=()=>{reject();};}else{resolve();}});},loadOneAfterAnother:async function(arr,name){for(let i=0;i<arr.length;i++){const item=arr[i];await this.loadScript(item,name+i);}},config:async function({region,env}){if(!["test","prod"].includes(env))throw new Error("Unexpected env: "+env);const libs={"MEX-1":["https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js","https://js.openpay.mx/openpay.v1.min.js","https://js.openpay.mx/openpay-data.v1.min.js",],};if(!libs[region])throw new Error("Region not found");switch(region){case "MEX-1":await this.loadOneAfterAnother(libs[region],"pagsmileCC-MEX-1");let config={test:{id:"mjoq965x33ul3gxf8vpt",key:"pk_a77e298689a84495b4611a51b6df1f4c"},prod:{id:"mtg8r6gnf6jgta6n1uq4",key:"pk_99341d6c181f4109920a933a5e1dabc5"},};if(env==="test")window.OpenPay.setSandboxMode(true);window.OpenPay.setId(config[env].id);window.OpenPay.setApiKey(config[env].key);return window.OpenPay?.deviceData?.setup("payment-form");default:throw new Error("Region not found");}},}}